/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <string.h>
#include <stdio.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <libnotify/notify.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"
#include "main.h"
#include "pixmap.h"

GtkStatusIcon *statusicon = NULL;
NotifyNotification *notify = NULL;

gboolean g_IsNotifyOsd = FALSE;

gboolean is_notify_osd()
{
  gchar *name;
  gchar *vendor;
  gchar *version;
  gchar *spec_version;
  gboolean retval = FALSE;

  notify_get_server_info(&name, &vendor, &version, &spec_version);
  g_print("Name: %s\t", name);
//  retval = !(g_strcmp0("notify-osd", name));
  retval = !(strcmp("notify-osd", name));
  g_free((gpointer) name);
  g_free((gpointer) vendor);
  g_free((gpointer) version);
  g_free((gpointer) spec_version);

  g_IsNotifyOsd = retval;

  if (g_IsNotifyOsd)
  {
    g_print("is  notify-osd\n");
  }
  else
  {
    g_print("not notify-osd\n");
  }

  return retval;

}

static void notify_action(NotifyNotification * notify, gchar * action, gpointer user_data)
{
}

void show_notification(const gchar * summary, const gchar * message, const gchar * action, gint timeout, GCallback handler)
{
  NotifyActionCallback callback;
  //GdkScreen *screen;
  //GdkRectangle area;

  if (notify_is_initted() == FALSE)
    return;

  if (notify)
  {
    g_signal_handlers_destroy(notify);
    notify_notification_close(notify, NULL);
  }

  // notify = notify_notification_new(summary, message, "3dspusbWB", NULL);
  notify = notify_notification_new_with_status_icon(summary, message, "3dspusbWB", statusicon);

//#ifdef TIMEOUTANDACTION
  if (!g_IsNotifyOsd)
  {

    notify_notification_set_timeout(notify, timeout);

    /*if (gtk_status_icon_get_visible(statusicon) == TRUE)
       {
       gtk_status_icon_get_geometry(statusicon, &screen, &area, NULL);

       notify_notification_set_hint_int32(notify, "x", area.x + area.width / 2);
       notify_notification_set_hint_int32(notify, "y", area.y + area.height / 2);
       } */

    notify_notification_set_urgency(notify, NOTIFY_URGENCY_NORMAL);

    callback = handler ? NOTIFY_ACTION_CALLBACK(handler) : notify_action;

    notify_notification_add_action(notify, "default", "action", callback, NULL, NULL);
    if (action != NULL)
      notify_notification_add_action(notify, "button", action, callback, NULL, NULL);

  }
//#endif

  notify_notification_show(notify, NULL);
}

void close_notification(void)
{
  if (notify)
  {
    g_signal_handlers_destroy(notify);
    notify_notification_close(notify, NULL);
    notify = NULL;
  }
}

GtkStatusIcon *init_notification(void)
{
  notify_init("uwb");
  is_notify_osd();

  statusicon = gtk_status_icon_new();
  g_object_unref(statusicon);

//  statusicon = gtk_status_icon_new_from_icon_name("TdspUsbWB.png");
//  statusicon = gtk_status_icon_new_from_file("TdspUsbWB.png");
  statusicon = gtk_status_icon_new_from_file("/usr/share/pixmaps/3dspusbWB.png");

  gtk_status_icon_set_tooltip(statusicon, _("Bluetooth and WLAN"));

  return statusicon;
}

void cleanup_notification(void)
{
  close_notification();

  g_object_unref(statusicon);

  notify_uninit();
}

void show_icon(void)
{
  gtk_status_icon_set_visible(statusicon, TRUE);
}

void hide_icon(void)
{
  gtk_status_icon_set_visible(statusicon, FALSE);
}

void adjust_icon(gint trayicocolor)
{
  GdkPixbuf *logo_pixbuf;
  switch (trayicocolor)
  {
  case 0:
    logo_pixbuf = gdk_pixbuf_new_from_xpm_data((const char **) TdspWBNew_green_xpm);
    break;
  case 1:
    logo_pixbuf = gdk_pixbuf_new_from_xpm_data((const char **) ico00001_red_xpm);
//        gtk_status_icon_set_from_pixbuf(statusicon,logo_pixbuf );
    break;
  case 2:
    logo_pixbuf = gdk_pixbuf_new_from_xpm_data((const char **) icon_gray_xpm);
    break;
  default:
    return;
  }
  gtk_status_icon_set_from_pixbuf(statusicon, logo_pixbuf);
  g_object_unref(logo_pixbuf);
  return;
}

/*void adjust_icon(gint trayicocolor)
{
  switch (trayicocolor)
    {
    case 0:
      gtk_status_icon_set_from_file(statusicon, "TdspUsbWB.png");
      break;
    case 1:
      gtk_status_icon_set_from_file(statusicon, "TdspUsbWB2.png");
      break;
    case 2:
      gtk_status_icon_set_from_file(statusicon, "TdspUsbWB2.png");
      break;
    default:
      break;
    }
}*/

void enable_blinking(void)
{
  gtk_status_icon_set_blinking(statusicon, TRUE);
}

void disable_blinking(void)
{
  gtk_status_icon_set_blinking(statusicon, FALSE);
}

gboolean query_blinking(void)
{
  return gtk_status_icon_get_blinking(statusicon);
}

void adjust_tooltip_text(gint state)
{
  THISFUNCBECALLED;
  switch (state)
  {
  case (BLUETOOTH_ENABLE_WLAN_DISABLE):
    gtk_status_icon_set_tooltip(statusicon, _("Bluetooth Card"));
    break;
  case (BLUETOOTH_DISABLE_WLAN_ENABLE):
    gtk_status_icon_set_tooltip(statusicon, _("WLAN Card"));
    break;
  case (BLUETOOTH_ENABLE_WLAN_ENABLE):
    gtk_status_icon_set_tooltip(statusicon, _("Bluetooth and Wlan"));
    break;
  case (BLUETOOTH_DISABLE_WLAN_DISABLE):
    gtk_status_icon_set_tooltip(statusicon, _("Bluetooth and Wlan"));
    break;
  case (BLUETOOTH_WLAN_ERROR):
    gtk_status_icon_set_tooltip(statusicon, _("3DSP Card Error"));
    break;
  default:
    debug("error state\n");
  }
  return;
}

/*#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)*/

GtkWidget *create_menu1(void)
{
  GtkWidget *menu1;
  GtkWidget *bluetooth1;
  GtkWidget *wlan1;
  GtkWidget *coexist1;
  GtkWidget *unplug1;
  GtkWidget *_________1;
  GtkWidget *about1;
  GtkWidget *exit1;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new();

  menu1 = gtk_menu_new();

  bluetooth1 = gtk_check_menu_item_new_with_mnemonic(_("_Bluetooth"));
  if (g_allowedmodes[0])
    gtk_widget_show(bluetooth1);
  gtk_container_add(GTK_CONTAINER(menu1), bluetooth1);
  gtk_tooltips_set_tip(tooltips, bluetooth1, _("Bluetooth Card"), NULL);

  wlan1 = gtk_check_menu_item_new_with_mnemonic(_("_Wlan"));
  if (g_allowedmodes[1])
    gtk_widget_show(wlan1);
  gtk_container_add(GTK_CONTAINER(menu1), wlan1);
  gtk_tooltips_set_tip(tooltips, wlan1, _("WLAN Card"), NULL);

  coexist1 = gtk_check_menu_item_new_with_mnemonic(_("_Coexist"));
  if (g_allowedmodes[2])
    gtk_widget_show(coexist1);
  gtk_container_add(GTK_CONTAINER(menu1), coexist1);
  gtk_tooltips_set_tip(tooltips, coexist1, _("Bluetooth and Wlan"), NULL);

  unplug1 = gtk_check_menu_item_new_with_mnemonic(_("_Unplug"));
  gtk_widget_show(unplug1);
  gtk_container_add(GTK_CONTAINER(menu1), unplug1);
  gtk_tooltips_set_tip(tooltips, unplug1, _("Bluetooth and Wlan"), NULL);

  _________1 = gtk_separator_menu_item_new();
  gtk_widget_show(_________1);
  gtk_container_add(GTK_CONTAINER(menu1), _________1);
  gtk_widget_set_sensitive(_________1, FALSE);

  about1 = gtk_menu_item_new_with_mnemonic(_("_About"));
  gtk_widget_show(about1);
  gtk_container_add(GTK_CONTAINER(menu1), about1);
  gtk_tooltips_set_tip(tooltips, about1, _("About"), NULL);

  exit1 = gtk_menu_item_new_with_mnemonic(_("E_xit"));
  gtk_widget_show(exit1);
  gtk_container_add(GTK_CONTAINER(menu1), exit1);
  gtk_tooltips_set_tip(tooltips, exit1, _("Exit"), NULL);

  g_signal_connect((gpointer) bluetooth1, "activate", G_CALLBACK(on_bluetooth_activate), NULL);
  g_signal_connect((gpointer) wlan1, "activate", G_CALLBACK(on_wlan1_activate), NULL);
  g_signal_connect((gpointer) coexist1, "activate", G_CALLBACK(on_coexist1_activate), NULL);
  g_signal_connect((gpointer) unplug1, "activate", G_CALLBACK(on_unplug1_activate), NULL);
  g_signal_connect((gpointer) about1, "activate", G_CALLBACK(on_about1_activate), NULL);
  g_signal_connect((gpointer) exit1, "activate", G_CALLBACK(on_exit1_activate), NULL);

  /* Store poginters to all widgets, for use by lookup_widget(). 
     GLADE_HOOKUP_OBJECT_NO_REF (menu1, menu1, "menu1");
     GLADE_HOOKUP_OBJECT (menu1, bluetooth1, "bluetooth1");
     GLADE_HOOKUP_OBJECT (menu1, wlan1, "wlan1");
     GLADE_HOOKUP_OBJECT (menu1, coexist1, "coexist1");
     GLADE_HOOKUP_OBJECT (menu1, unplug1, "unplug1");
     GLADE_HOOKUP_OBJECT (menu1, _________1, "_________1");
     GLADE_HOOKUP_OBJECT (menu1, about1, "about1");
     GLADE_HOOKUP_OBJECT (menu1, exit1, "exit1");
     GLADE_HOOKUP_OBJECT_NO_REF (menu1, tooltips, "tooltips"); */

  tdspuwbmenu.bluetooth = bluetooth1;
  tdspuwbmenu.wlan = wlan1;
  tdspuwbmenu.coexist = coexist1;
  tdspuwbmenu.unplug = unplug1;
  tdspuwbmenu.about = about1;
  tdspuwbmenu.exit = exit1;
  tdspuwbmenu.mainmenu = menu1;

  return menu1;
}
