#ifndef INTERFACE_H
#define INTERFACE_H
/************************************************************************** 
 * FILENAME:     interface.h          
 * CREATE DATE:  2009/12/24 
 * PURPOSE:      the headfile of interface.c 
 *                ... 
 *  
 * AUTHORS:      3dsp <ritow.qi@3dsp.com.cn> 
 * 
 * NOTES:        description of constraints when using functions of this file 
 * 
 **************************************************************************/

/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

void show_notification(const gchar * summary, const gchar * message, const gchar * action, gint timeout, GCallback handler);

void close_notification(void);

GtkStatusIcon *init_notification(void);

void cleanup_notification(void);

void show_icon(void);

void hide_icon(void);

void adjust_icon(gint trayicocolor);

void enable_blinking(void);

void disable_blinking(void);

gboolean query_blinking(void);

void adjust_tooltip_text();

GtkWidget *create_menu1(void);

#endif
